#!/bin/bash
new_args=$(echo "$@" |  sed 's/-[^I][A-Z,a-z]*//g' )
ftn -cpp -d B $new_args 2>&1 |  sed 's/\s*$//g' | sed 's/^ftn.*/&:/g'  | grep "^ftn" -A 1 | sed 's/^  /\n   0  |     Lorem\n      |              1\nError: /g' | sed 's/.*File = //g' | sed 's/, Line = /:/g' |  sed 's/, Column = /:/g' | sed '/^--/d' 
